discord_auth_token = "your discord auth token should go here"
guild_id = "your discords guild id should go here"
icon_url = "url pointing to the image that sits in the footer"
activity_text = "custom activity text"
path_to_json = "your path"
channel_id = "your vouch_channel id"
command_prefix = "whatever your command prefix should be, it will also use slash commands!"