name: Deploy Discord Bot to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -e  # Stop the script on the first error
          sudo systemctl daemon-reload
          cd ${{ secrets.AWS_PATH }}
          git pull origin master
          source bot-env/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart discord-bot
